/**
 * CleanCity 360 Automated Integration Test Suite
 * Tests full citizen, admin, and AI pipelines
 */

const http = require('http');

const BASE_URL = 'http://127.0.0.1:5000';

function makeRequest(method, path, data = null, headers = {}) {
  return new Promise((resolve, reject) => {
    const url = new URL(path, BASE_URL);
    const options = {
      method,
      hostname: url.hostname,
      port: url.port,
      path: url.pathname + url.search,
      headers: {
        'Content-Type': 'application/json',
        ...headers
      }
    };

    const req = http.request(options, (res) => {
      let body = '';
      res.on('data', (chunk) => (body += chunk));
      res.on('end', () => {
        try {
          const parsed = JSON.parse(body);
          resolve({ status: res.statusCode, body: parsed });
        } catch (e) {
          resolve({ status: res.statusCode, body });
        }
      });
    });

    req.on('error', reject);

    if (data) {
      req.write(typeof data === 'string' ? data : JSON.stringify(data));
    }
    req.end();
  });
}

async function runTests() {
  console.log('====================================================');
  console.log('🧪 Running CleanCity 360 End-to-End Integration Tests');
  console.log('====================================================\n');

  let passed = 0;
  let failed = 0;

  const test = async (name, fn) => {
    try {
      process.stdout.write(`• ${name}... `);
      await fn();
      console.log('✅ PASS');
      passed++;
    } catch (err) {
      console.log(`❌ FAIL: ${err.message}`);
      failed++;
    }
  };

  try {
    // 1. Healthcheck
    await test('GET /api/health returns 200 OK', async () => {
      const res = await makeRequest('GET', '/api/health');
      if (res.status !== 200 || res.body.status !== 'ok') {
        throw new Error(`Expected 200 ok, got ${res.status}`);
      }
    });

    // 2. Categories
    await test('GET /api/ai/categories returns 7 standard categories', async () => {
      const res = await makeRequest('GET', '/api/ai/categories');
      if (!res.body.success || res.body.categories.length !== 7) {
        throw new Error('Expected 7 waste categories');
      }
    });

    // 3. AI Preset Analysis
    await test('POST /api/ai/analyze-preset identifies Plastic with confidence', async () => {
      const res = await makeRequest('POST', '/api/ai/analyze-preset', { presetType: 'plastic' });
      if (!res.body.success || res.body.analysis.category !== 'Plastic' || res.body.analysis.confidence < 0.7) {
        throw new Error('AI analysis failed or confidence too low');
      }
    });

    // 4. Citizen Demo Login
    let citizenToken = '';
    await test('POST /api/auth/demo-login (Citizen) returns valid JWT', async () => {
      const res = await makeRequest('POST', '/api/auth/demo-login', { role: 'citizen' });
      if (!res.body.success || !res.body.token || res.body.user.role !== 'citizen') {
        throw new Error('Citizen demo login failed');
      }
      citizenToken = res.body.token;
    });

    // 5. Admin Demo Login
    let adminToken = '';
    await test('POST /api/auth/demo-login (Admin) returns valid JWT', async () => {
      const res = await makeRequest('POST', '/api/auth/demo-login', { role: 'admin' });
      if (!res.body.success || !res.body.token || res.body.user.role !== 'admin') {
        throw new Error('Admin demo login failed');
      }
      adminToken = res.body.token;
    });

    // 6. Create Complaint
    let createdComplaintId = '';
    await test('POST /api/complaints creates a new complaint with ID', async () => {
      const payload = {
        category: 'Plastic',
        description: 'Test complaint generated by automated integration test suite.',
        imageUrl: '/uploads/sample-plastic-bottles.svg',
        latitude: 28.6328,
        longitude: 77.2197,
        address: 'Connaught Place Outer Circle, Ward 1',
        landmark: 'Near Test Marker',
        priority: 'High',
        aiSuggestedCategory: 'Plastic',
        aiConfidence: 0.91
      };

      const res = await makeRequest('POST', '/api/complaints', payload, {
        Authorization: `Bearer ${citizenToken}`
      });

      if (!res.body.success || !res.body.complaint || !res.body.complaint.id) {
        throw new Error('Failed to create complaint');
      }
      createdComplaintId = res.body.complaint.id;
    });

    // 7. Public Tracking
    await test(`GET /api/complaints/track/${createdComplaintId} works without auth`, async () => {
      const res = await makeRequest('GET', `/api/complaints/track/${createdComplaintId}`);
      if (!res.body.success || res.body.complaint.status !== 'Reported') {
        throw new Error('Public tracking lookup failed');
      }
    });

    // 8. Admin Assign Worker
    await test(`PATCH /api/complaints/${createdComplaintId}/assign assigns worker and updates status`, async () => {
      const res = await makeRequest(
        'PATCH',
        `/api/complaints/${createdComplaintId}/assign`,
        { workerId: 1, notes: 'Automated test task dispatch' },
        { Authorization: `Bearer ${adminToken}` }
      );

      if (!res.body.success || res.body.complaint.status !== 'Assigned') {
        throw new Error('Failed to assign worker');
      }
    });

    // 9. Admin Update Status to In Progress and then Resolved
    await test(`PATCH /api/complaints/${createdComplaintId}/status advances to Resolved`, async () => {
      const res = await makeRequest(
        'PATCH',
        `/api/complaints/${createdComplaintId}/status`,
        {
          status: 'Resolved',
          notes: 'Test site successfully verified and cleared',
          resolutionImageUrl: '/uploads/sample-resolved-clean.svg'
        },
        { Authorization: `Bearer ${adminToken}` }
      );

      if (!res.body.success || res.body.complaint.status !== 'Resolved' || !res.body.complaint.resolved_at) {
        throw new Error('Failed to mark complaint as resolved');
      }
    });

    // 10. Analytics & Hotspots
    await test('GET /api/analytics/overview returns metrics & hotspot clusters', async () => {
      const res = await makeRequest('GET', '/api/analytics/overview', null, {
        Authorization: `Bearer ${adminToken}`
      });

      if (!res.body.success || !res.body.stats || !res.body.hotspots || res.body.hotspots.length === 0) {
        throw new Error('Analytics overview payload incomplete');
      }
    });

    console.log(`\n====================================================`);
    console.log(`Test Results: ${passed} Passed, ${failed} Failed`);
    console.log(`====================================================\n`);

    if (failed > 0) {
      process.exit(1);
    }
  } catch (err) {
    console.error('Fatal test runner error:', err);
    process.exit(1);
  }
}

// Check if server is running or start it
const req = http.get('http://127.0.0.1:5000/api/health', (res) => {
  runTests();
});
req.on('error', () => {
  console.log('Server not currently running on :5000. Launching temporary instance...');
  const { spawn } = require('child_process');
  const path = require('path');
  const srv = spawn('node', [path.join(__dirname, '../backend/server.js')], {
    stdio: 'inherit'
  });

  setTimeout(() => {
    runTests().then(() => {
      srv.kill();
      process.exit(0);
    });
  }, 2500);
});
